/**
 * Downloads the self-hosted webfonts and generates site/fonts/fonts.css.
 *
 * The map ships its own fonts rather than relying on whatever a device happens to have, so
 * the typography is identical on every screen and only the size changes. Both families are
 * SIL Open Font Licence 1.1; the licences are downloaded alongside the files as that licence
 * requires.
 *
 * Fetched from the Google Fonts CSS API rather than hand-copied URLs, so re-running this
 * picks up new font versions instead of pinning a stale hash forever.
 *
 * Run: npx tsx scripts/fetch-fonts.ts
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { repoRoot } from '../src/core/util/paths.js';

const fontsDir = path.join(repoRoot, 'site', 'fonts');

// Asking as a modern browser is what makes the API return woff2 rather than older formats.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36';

/**
 * Latin and Latin Extended only. Place names in the feed are romanised, but they carry
 * marks like the ḩ in "Laḩij" (U+1E29), which lives in latin-ext — without it those names
 * would silently fall back to a different face mid-word.
 */
const WANTED_SUBSETS = new Set(['latin', 'latin-ext']);

const FAMILIES = [
  {
    query: 'Fraunces:ital,opsz,wght@0,9..144,300..700;1,9..144,300..700',
    family: 'Fraunces',
    slug: 'fraunces',
    licence: 'https://raw.githubusercontent.com/google/fonts/main/ofl/fraunces/OFL.txt',
  },
  {
    query: 'Inter:wght@300..700',
    family: 'Inter',
    slug: 'inter',
    licence: 'https://raw.githubusercontent.com/google/fonts/main/ofl/inter/OFL.txt',
  },
];

interface Face {
  family: string;
  slug: string;
  subset: string;
  style: string;
  weight: string;
  unicodeRange: string;
  url: string;
  file: string;
}

async function get(url: string, accept: string): Promise<Response> {
  const response = await fetch(url, { headers: { 'user-agent': UA, accept } });
  if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
  return response;
}

const faces: Face[] = [];

for (const family of FAMILIES) {
  const css = await (
    await get(`https://fonts.googleapis.com/css2?family=${encodeURIComponent(family.query)}&display=swap`, 'text/css')
  ).text();

  // Each @font-face is preceded by a /* subset */ comment naming its coverage.
  const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([\s\S]*?)\}/g)];
  if (blocks.length === 0) throw new Error(`No @font-face blocks returned for ${family.family}`);

  for (const [, subset, body] of blocks) {
    if (!WANTED_SUBSETS.has(subset as string)) continue;
    const url = /url\((https:\/\/[^)]+)\)/.exec(body as string)?.[1];
    const unicodeRange = /unicode-range:\s*([^;]+);/.exec(body as string)?.[1]?.trim();
    const style = /font-style:\s*([^;]+);/.exec(body as string)?.[1]?.trim() ?? 'normal';
    const weight = /font-weight:\s*([^;]+);/.exec(body as string)?.[1]?.trim() ?? '400';
    if (!url || !unicodeRange) throw new Error(`Incomplete @font-face for ${family.family}/${subset}`);

    const file = `${family.slug}-${style === 'italic' ? 'italic-' : ''}${subset}.woff2`;
    faces.push({ family: family.family, slug: family.slug, subset: subset as string, style, weight, unicodeRange, url, file });
  }

  const licence = await (await get(family.licence, 'text/plain')).text();
  writeFileSync(path.join(fontsDir, `${family.slug}-OFL.txt`), licence, 'utf-8');
}

let total = 0;
for (const face of faces) {
  const bytes = new Uint8Array(await (await get(face.url, 'font/woff2')).arrayBuffer());
  // wOF2 magic number — a redirect to an HTML error page would otherwise be written silently.
  if (!(bytes[0] === 0x77 && bytes[1] === 0x4f && bytes[2] === 0x46 && bytes[3] === 0x32)) {
    throw new Error(`${face.file} is not a woff2 file`);
  }
  writeFileSync(path.join(fontsDir, face.file), bytes);
  total += bytes.length;
  console.log(`${face.file}: ${(bytes.length / 1024).toFixed(0)} KB`);
}

const css = [
  '/*',
  ' * Generated by scripts/fetch-fonts.ts — do not edit by hand.',
  ' *',
  ' * Fraunces and Inter, both SIL Open Font Licence 1.1 (see the OFL.txt files beside this).',
  ' * Self-hosted so every device renders the same typography; only the size changes per screen.',
  ' */',
  '',
  ...faces.map((face) =>
    [
      '@font-face {',
      `  font-family: '${face.family}';`,
      `  font-style: ${face.style};`,
      `  font-weight: ${face.weight};`,
      '  font-display: swap;',
      `  src: url('${face.file}') format('woff2');`,
      `  unicode-range: ${face.unicodeRange};`,
      '}',
    ].join('\n'),
  ),
].join('\n');

writeFileSync(path.join(fontsDir, 'fonts.css'), `${css}\n`, 'utf-8');
console.log(`\n${faces.length} faces, ${(total / 1024).toFixed(0)} KB total. Wrote site/fonts/fonts.css`);
